language: node_js
node_js:
    - "8.10.0"
cache:
  directories:
  - node_modules
script: node dblp-cite.js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
  on:
    branch: master
env:
  matrix:
    secure: VTClSBJ+t/rqZ0lG7UYkladzDTidhHE0K3RO1teZa9R2rdSKmKVuX8lTUCcgneJzSWiIH1gpVSacIkyYc7pFQHQQ1Cfxf37vLIieIokjXPOpZBE5wYhKodFpYZc8fV85ZjKUSotQjOvTnxGBQRn/qKA4hyry9YtdVsfF5GCuF1jS0eEWt4Wtbq9v3KDN7FP0LuLKBuO9avFFSTD3LhXcPKDVX7wprGtaWpdHNQZTZeDPj+pALtRRjMqGWQT0fuutAJpP1t5pe5UKPPX4Fcl6MkRXrtB7aE41wc075xSXq5ChABuxgRaHFErHdvJtqU+RTBdbYO3GdqmU931Y1BskaBxkZEveG9fdF2ef/ZzPH2L+VnZsHLjVGx+htSm8GJQ6siO7J9bc68jWszUAiRriDpvs2jHKClbD/ZAAa7llDHxIqW2W8d/K/ZdcpkTlFOGQwz6hD62p1hAt31Qcnf3UJeRQv44vpN+MUoxXOuLx2o9d14RZQ/wmUpLPEmJiWlXI2ZMEPF53edpAkyrGtAZePBEKoN2ChCzELkHpUpRuPaRDlljPVy5F1z50YUTGDWi5CV0JXvxwOicPmCCVR/a9uZRTI6TQLB6UU0RHw4gmtCSvekJ5qd6ee6qUQIC7EqM9HnWUlpM98sMggdbtKnq7ZgNS3JiL9bWz6xoXf87l5Ck=
